### ISSUE TITLE
Continuing with diagrams for 2 iteration

### ISSUE THREAD

**Issue by klomucaj** [klomucaj/LoyaltyPlatform#28]

**Comment by Rineesa** [comment]
Working with the existing and new diagrams for the platform

**Comment by klomucaj** [comment]
At this point we have finished with the Use Case diagram and moved on into Sequence Diagram and Class Diagram

**Comment by klomucaj** [comment]
Sequence Diagram is finished and we will move on with the last diagram which is "Class Diagram"

**Comment by Rineesa** [comment]
The additional work done on the 2nd Iteration, except working on finishing use cases for the Backoffice and finalizing them, is touching the secondary actors from the Backoffice and Consumers.
Adding up additional use cases for both actors mentioned above, developing them into sequence diagrams up till class diagrams the work was done in a period of 2 weeks, with all the diagrams finished and extra following up in the code.
