### ISSUE TITLE
Updating "loyalty programs"

### ISSUE THREAD

**Issue by klomucaj** [klomucaj/LoyaltyPlatform#31]
- [x] Cashback Program
- [x] Level Program
- [x] Point Program
- [x] Premium Program

**Comment by klomucaj** [comment]
I finished all classes about "Premium Program"

**Comment by klomucaj** [comment]
Now I am working with "cashback program" adding and fixing some piece of code

**Comment by klomucaj** [comment]
Today I finished all part of code for "Cashback Program"

**Comment by Rineesa** [comment]
Point Program classes all uploaded and currently working only on the Levels Program classes.

**Comment by Rineesa** [comment]
Finished with the Level Program

**Comment by Rineesa** [comment]
**_Finished with Loyalty Platform Programs_**.
