### ISSUE TITLE
List of actors and their roles

### ISSUE THREAD

**Issue by klomucaj** [klomucaj/LoyaltyPlatform#6]

**Comment by Rineesa** [comment]
The list of actors is divided into:

1. Primary actors:
         - consumer
                  objective: obtain benefits from using the service
         - owner
                  objective: collect information for advertising campaigns
                  objective: loyalty
          - administrator
                  objective: maintain the various structures of the company in an orderly manner (external, internal relations, management of company data)

2. Secondary actors:

     - messaging/email system…
     -   payment/banking systems
     -  retailer's website (online shop)
     -  other companies (in the context of the coalition program)
